version: "3.2"

services:
  influx:
    image: influxdb
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=stock
      - INFLUXDB_DATA_QUERY_LOG_ENABLED=1
    volumes:
      - ".docker:/var/lib/influxdb"
